print("=" * 80)
print("No main.py was found so one was created!")
print("Add your own code to this file: /home/jaaxx/Documents/Obsidian-Test/MY-OBSIDIAN/main.py")
print("=" * 80)
input("Key enter to close.")